export const
	AXIS = 'a',
	VIEW_CONTAINER_ELEMENT = 'vC',
	HANDLER_CONTAINER_ELEMENT = 'hC',
	SIZE_CHECKING_DEBOUNCER = 'c',
	SIZE_WATCHER = 'o',
	RESIZING = 'r',
	HEAD_VIEW = 'hV',
	REAR_VIEW = 'rV',
	DIRECTION_FLAG = 'f',
	DIRECTION = 'd',
	LAST_WIDTH = 'lW',
	LAST_HEIGHT = 'lH',
	VIEW_MAP = 'v',
	INTERFACE = '$';

export const
	RESET = 'R',
	ADJUST = 'A',
	UPDATE_LAST_SIZE = 'U',
	MOUNT = 'M',
	UNMOUNT = 'U',
	APPEND_VIEW = 'VA',
	REMOVE_VIEW = 'VR',
	ASSERT_OWNED_VIEW = 'S';
